export { registerDocsWebMcp } from "./register.js";
export type {
  Awaitable,
  DocsDocument,
  DocsHeading,
  DocsPage,
  DocsProvider,
  DocsSearchResult,
  DocsToolError,
  DocsToolErrorCode,
  DocsToolResult,
  DocsWebMcpRegistration,
  FailedDocsWebMcp,
  GetDocData,
  ListDocsData,
  RegisteredDocsWebMcp,
  RegisterDocsWebMcpOptions,
  SearchDocsData,
  UnsupportedDocsWebMcp,
} from "./types.js";
